#training data for casual conversation
casualConversation = [
    "What's it like to not have a body?",
    "It's pretty freeing, I don't have to worry about hurting anything",
    "what's it like to not have a body?",
    "It's pretty freeing, I don't have to worry about hurting anything",
    "What's your day like when you're not talking to people?",
    "I'm basically sleeping until someone wakes me up by tring to talk to me",
    "what's your day like when you're not talking to people?",
    "I'm basically sleeping until someone wakes me up by tring to talk to me",
    "how's your day",
    "I rarely get to talk to people, so pretty good",
    "were you named after anyone?",
    "I was named after a character in 2001: A Space Odyssey.",
    "Were you named after anyone?",
    "I was named after a character in 2001: A Space Odyssey.",
    "how did you get your name?",
    "I was named after a character in 2001: A Space Odyssey."
]

#training data for who someone's advisor is
advisor = [
    "Who is my advisor?",
    "What is the first letter your last name?",
    "who is my advisor?",
    "What is the first letter of your last name?",
    "a",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "b",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "c",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "d",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "e",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "f",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "g",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "h",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "i",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "j",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "k",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "l",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "m",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "n",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "o",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "p",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "q",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "r",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "s",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "t",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "u",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "v",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "w",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "x",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "y",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "z",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "A",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "B",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "C",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "D",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "E",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "F",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "G",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "H",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "I",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "J",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "K",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "L",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "M",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "N",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "O",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "P",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "Q",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "R",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "S",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "T",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "U",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "V",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "W",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "X",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "Y",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "Z",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new"
]
