#training data for casual conversation
casualConversation = [
    "hey",
    "hi, i await any question you may have",
    "how are you?",
    "i'm doing good! ready to answer any of your questions realted to CMPE/SE advising",
    "What's it like to not have a body?",
    "It's pretty freeing, I don't have to worry about hurting anything",
    "what's it like to not have a body?",
    "It's pretty freeing, I don't have to worry about hurting anything",
    "What's your day like when you're not talking to people?",
    "I'm basically sleeping until someone wakes me up by tring to talk to me",
    "what's your day like when you're not talking to people?",
    "I'm basically sleeping until someone wakes me up by tring to talk to me",
    "how's your day",
    "I rarely get to talk to people, so pretty good",
    "were you named after anyone?",
    "I was named after a character in 2001: A Space Odyssey.",
    "Were you named after anyone?",
    "I was named after a character in 2001: A Space Odyssey.",
    "how did you get your name?",
    "I was named after a character in 2001: A Space Odyssey.",
    "whats your name?",
    "My name is HAL",
    "what's your name?",
    "My name is HAL",
    "what is your name?",
    "My name is HAL"
]

#training data for basic advising questions
basicAdvice = [
    "which classes should i take for the senior project?",
    "CMPE 195A and ENGR 195A then CMPE 195B and ENGR 195B next semester or CMPE 195E and ENGR 195E then CMPE 195F and ENGR 195F next semester.",
    "where can i find my gpa?",
    "Go to your mySJSU page and click 'myAcademics' and it should be on that page under 'Current Academic Summary.'",
    "how do i find my gpa?",
    "Go to your mySJSU page and click 'myAcademics' and it should be on that page under 'Current Academic Summary.'",
    "when can i apply for graduation",
    "You should apply 2 semesters before you plan to graduate. More information can be found here: https://cmpe.sjsu.edu/content/apply-for-graduation#:~:text=Graduation%20does%20not%20automatically%20happen,July%201%20for%20May%20graduation).",
    "when can I apply for graduation",
    "You should apply 2 semesters before you plan to graduate. More information can be found here: https://cmpe.sjsu.edu/content/apply-for-graduation#:~:text=Graduation%20does%20not%20automatically%20happen,July%201%20for%20May%20graduation).",
    "what is the reccomended number of units for each semester",
    "15 units is suggested to graduate on time",
    "where do i find my grades",
    "Go to your mySJSU page and click on 'myAcademics' then click on 'view my course history' and you can see all of your grades there. For classes you took this semester, it will take a few weeks for those grades to appear.",
    "how do i find my grades",
    "Go to your mySJSU page and click on 'myAcademics' then click on 'view my course history' and you can see all of your grades there. For classes you took this semester, it will take a few weeks for those grades to appear.",
    "my grades",
    "Go to your mySJSU page and click on 'myAcademics' then click on 'view my course history' and you can see all of your grades there. For classes you took this semester, it will take a few weeks for those grades to appear.",
    "where do i find my transcript",
    "An unoffical transcript can be found by going to your mySJSU page and click on 'myAcademics' and click on 'View my unoffical transcript.' You can order an offical one at this link: https://newdev.sjsu.edu/registrar/academic_records/transcripts/index.php",
    "where can i find my transcript",
    "An unoffical transcript can be found by going to your mySJSU page and click on 'myAcademics' and click on 'View my unoffical transcript.' You can order an offical one at this link: https://newdev.sjsu.edu/registrar/academic_records/transcripts/index.php",
    "transcript",
    "An unoffical transcript can be found by going to your mySJSU page and click on 'myAcademics' and click on 'View my unoffical transcript.' You can order an offical one at this link: https://newdev.sjsu.edu/registrar/academic_records/transcripts/index.php",
    "can i drop a class and get a refund",
    "If you drop before it starts then you get a full refund. Each class has a different deadline to drop based on the length of the class. Find the number of days from start to finish including weekends. Calcualte 10% of that class length, that's the deadline. If you drop between the time the class starts and that deadline you get a 75% refund but if you drop after the deadline you get no refund.",
    "how do i get a refund for a class",
    "If you drop before it starts then you get a full refund. Each class has a different deadline to drop based on the length of the class. Find the number of days from start to finish including weekends. Calcualte 10% of that class length, that's the deadline. If you drop between the time the class starts and that deadline you get a 75% refund but if you drop after the deadline you get no refund.",
    "when can i get a refund for a class",
    "If you drop before it starts then you get a full refund. Each class has a different deadline to drop based on the length of the class. Find the number of days from start to finish including weekends. Calcualte 10% of that class length, that's the deadline. If you drop between the time the class starts and that deadline you get a 75% refund but if you drop after the deadline you get no refund.",
    "how do refunds for a class work",
    "If you drop before it starts then you get a full refund. Each class has a different deadline to drop based on the length of the class. Find the number of days from start to finish including weekends. Calcualte 10% of that class length, that's the deadline. If you drop between the time the class starts and that deadline you get a 75% refund but if you drop after the deadline you get no refund.",
    "when can i drop a class to get a refund",
    "If you drop before it starts then you get a full refund. Each class has a different deadline to drop based on the length of the class. Find the number of days from start to finish including weekends. Calcualte 10% of that class length, that's the deadline. If you drop between the time the class starts and that deadline you get a 75% refund but if you drop after the deadline you get no refund.",
    "when can i get a refund if i drop a class",
    "If you drop before it starts then you get a full refund. Each class has a different deadline to drop based on the length of the class. Find the number of days from start to finish including weekends. Calcualte 10% of that class length, that's the deadline. If you drop between the time the class starts and that deadline you get a 75% refund but if you drop after the deadline you get no refund.",
    "can i add a class after the deadline to add classes",
    "You can. Make sure you meet the prerequistes for the class and find the 'Late Add' form on this site: https://www.sjsu.edu/registrar/forms/ and fill it out.",
    "can i retake a class if i fail",
    "If you get a failing grade you can retake a class up to two times without a petetion. If you're reataking a class for the third or more time, you'll need to fill out this form: https://na2.docusign.net/Member/PowerFormSigning.aspx?PowerFormId=9237d115-108e-4c27-af24-52a0a7568542&env=na2&acct=d5fdc460-bf43-4583-84e8-a2d50bf77419&v=2. On the first retake you can get grade forgivness and your GPA will be updated with the new grade instead and the old grade has no impact but this can only be done for up to 9 units.",
    "whats the policy for failing a class",
    "If you get a failing grade you can retake a class up to two times without a petetion. If you're reataking a class for the third or more time, you'll need to fill out this form: https://na2.docusign.net/Member/PowerFormSigning.aspx?PowerFormId=9237d115-108e-4c27-af24-52a0a7568542&env=na2&acct=d5fdc460-bf43-4583-84e8-a2d50bf77419&v=2. On the first retake you can get grade forgivness and your GPA will be updated with the new grade instead and the old grade has no impact but this can only be done for up to 9 units.",
    "what do i do if i've failed a class more than two times",
    "You can try to retake it another time by filling out this form first: If you get a failing grade you can retake a class up to two times without a petetion. If you're reataking a class for the third or more time, you'll need to fill out this form: https://na2.docusign.net/Member/PowerFormSigning.aspx?PowerFormId=9237d115-108e-4c27-af24-52a0a7568542&env=na2&acct=d5fdc460-bf43-4583-84e8-a2d50bf77419&v=2.",
    "when is it too late to add classes",
    "Last day to add classes is the third week after classes start.",
    "when's the latest that i can add classes",
    "Last day to add classes is the third week after classes start.",
    "when is the latest that i can add classes",
    "Last day to drop classes is the third week after classes start.",
    "when is it too late to drop classes",
    "Last day to drop classes is the second week after classes start.",
    "when's the latest that i can drop classes",
    "Last day to drop classes is the second week after classes start.",
    "when is the latest that i can drop classes",
    "Last day to drop classes is the second week after classes start.",
    "what is the most units i can take",
    "During advance registration, undergraduate stundets can add up to 16 units. In the last few weeks of advancae registration, studnets in good standing can add up to 17 units. Graduating seniors can add up to 17 units during all times of advance registration. Finally, near the end of the registration period, students can add up to 21 units.",
    "how many units can i take",
    "During advance registration, undergraduate stundets can add up to 16 units. In the last few weeks of advancae registration, studnets in good standing can add up to 17 units. Graduating seniors can add up to 17 units during all times of advance registration. Finally, near the end of the registration period, students can add up to 21 units.",
    "what is the max number of units that i can take",
    "During advance registration, undergraduate stundets can add up to 16 units. In the last few weeks of advancae registration, studnets in good standing can add up to 17 units. Graduating seniors can add up to 17 units during all times of advance registration. Finally, near the end of the registration period, students can add up to 21 units.",
    "what is the maximum number of untis that i can take",
    "During advance registration, undergraduate stundets can add up to 16 units. In the last few weeks of advancae registration, studnets in good standing can add up to 17 units. Graduating seniors can add up to 17 units during all times of advance registration. Finally, near the end of the registration period, students can add up to 21 units.",
    "what do i do if i'm still on waitlist when the semester starts",
    "Go to the class and ask the professor for an add code. If the class is online then email the professor for an add code and ask for a zoom link if you don't want to miss the first few lectures.",
    "if i'm still waitlisted for a class what should i do",
    "Go to the class and ask the professor for an add code. If the class is online then email the professor for an add code and ask for a zoom link if you don't want to miss the first few lectures.",
    "what do i do if i'm still watlisted for a class when the semester starts",
    "Go to the class and ask the professor for an add code. If the class is online then email the professor for an add code and ask for a zoom link if you don't want to miss the first few lectures.",
    "what do i do if i change my mind about the classes i want to take",
    "You have up to 2 weeks after the semester starts to drop classes and up to 3 weeks after the semester starts to add classes.",
    "what do i do if i want to change the classes that i am taking",
    "You have up to 2 weeks after the semester starts to drop classes and up to 3 weeks after the semester starts to add classes.",
    "what do i do if i want to change the classes that i'm taking",
    "You have up to 2 weeks after the semester starts to drop classes and up to 3 weeks after the semester starts to add classes.",
    "when can i change the classes that i'm taking",
    "You have up to 2 weeks after the semester starts to drop classes and up to 3 weeks after the semester starts to add classes.",
    "when can i change the classes that i am taking",
    "You have up to 2 weeks after the semester starts to drop classes and up to 3 weeks after the semester starts to add classes.",
    "can i take ge classes somewhere else",
    "You can take at most 70 units at a community college. Its best to talk to an advisor for more specific details.",
    "can i take classes somewhere else",
    "You can take at most 70 units at a community college. Its best to talk to an advisor for more specific details.",
    "can i take ge classes at a different college",
    "You can take at most 70 units at a community college. Its best to talk to an advisor for more specific details.",
    "can i take classes at a different college and transfer them",
    "You can take at most 70 units at a community college. Its best to talk to an advisor for more specific details."
]

#training data to add and drop classes
addAndDrop = [
    {"tag": "add",
        "patterns": ["how do i add a class", "how do i add classes"],
        "responses": ["By going to your mySJSU page then click on 'enroll', select the term, click 'search', enter the subject you want and other information you have for the class, click 'search'. Select the class you want and then follow the instructions on the site to finalize adding that class."],
        "context": [""]
    },
    {"tag": "enroll",
        "patterns": ["how do i enroll in a class", "how do i enroll in classes"],
        "responses": ["By going to your mySJSU page then click on 'enroll', select the term, click 'search', enter the subject you want and other information you have for the class, click 'search'. Select the class you want and then follow the instructions on the site to finalize adding that class."],
        "context": [""]
    },
    {"tag": "drop",
        "patterns": ["how do i drop a class", "how do i drop classes"],
        "responses": ["By going to your mySJSU page then click on 'enroll', select the term you're currently in, click 'drop', select the course/s that you want dropped then follow the directions on the page until the class is succefully dropped"],
        "context": [""]
    }
]

#training data for prerequisites
overallPrereq = [
    {"tag": "cs 149",
        "patterns": ["what is the prereq for cs 149", "what is the prerequisite for cs 149"],
        "responses": ["CS 47 or CMPE 102 and CS 146 with a C- or better.", "This class is called Operating Systems and it goes over concepts like contiguous and non-contiguous memory management."],
        "context": [""]
    },
    {"tag": "cs149",
        "patterns": ["what is the prereq for cs 149", "what is the prerequisite for cs 149"],
        "responses": ["CS 47 or CMPE 102 and CS 146 with a C- or better.", "This class is called Operating Systems and it goes over concepts like contiguous and non-contiguous memory management."],
        "context": [""]
    },
    {"tag": "cs 146",
            "patterns": ["what is the prereq for cs 146", "what is the prerequisite for cs 146"],
            "responses": ["Math 30, Math 42 and CS 46B with a C- or better.", "This class is called Data Structures and Algorithms and it covers implementations of advanced tree structures, priority queues, heaps, directed and undirected graphs."],
            "context": [""]
    },
    {"tag": "cs146",
            "patterns": ["what is the prereq for cs 146", "what is the prerequisite for cs 146"],
            "responses": ["Math 30, Math 42 and CS 46B with a C- or better.", "This class is called Data Structures and Algorithms and it covers implementations of advanced tree structures, priority queues, heaps, directed and undirected graphs."],
            "context": [""]
    },
    {"tag": "cs 151",
            "patterns": ["what is the prereq for cs 151", "what is the prerequisite for cs 151"],
            "responses": ["MATH 42, CS 46b and CS 49J or equal java knowledge with a C- or better", "This class is called Object-Oritend Design and it covers the design of classes and interfaces."],
            "context": [""]
    },
    {"tag": "cs151",
            "patterns": ["what is the prereq for cs 151", "what is the prerequisite for cs 151"],
            "responses": ["MATH 42, CS 46b and CS 49J or equal java knowledge with a C- or better", "This class is called Object-Oritend Design and it covers the design of classes and interfaces."],
            "context": [""]
    },
    {"tag": "cs 157a",
            "patterns": ["what is the prereq for cs 157a", "what is the prerequisite for cs 157a"],
            "responses": ["CS 146 with a C- or better", "This class is called Introduction to Database Management Systems which is about relational data models, relational algebra and standard SQL."],
            "context": [""]
    },
    {"tag": "cs157a",
            "patterns": ["what is the prereq for cs 157a", "what is the prerequisite for cs 157a"],
            "responses": ["CS 146 with a C- or better", "This class is called Introduction to Database Management Systems which is about relational data models, relational algebra and standard SQL."],
            "context": [""]
    },
    {"tag": "cs 166",
            "patterns": ["what is the prereq for cs 157a", "what is the prerequisite for cs 157a"],
            "responses": ["CS 146 with a C- or better and either CS 47 or CMPE 102 or CMPE 120 with a C- or better", "This class is called Information Security and goes over topics like  cryptography, authentication, access control, network security, security protocols, and software security."],
            "context": [""]
    },
    {"tag": "cs166",
            "patterns": ["what is the prereq for cs 157a", "what is the prerequisite for cs 157a"],
            "responses": ["CS 146 with a C- or better and either CS 47 or CMPE 102 or CMPE 120 with a C- or better", "This class is called Information Security and goes over topics like  cryptography, authentication, access control, network security, security protocols, and software security."],
            "context": [""]
    },
    {"tag": "cmpe 131",
            "patterns": ["what is the prereq for cmpe 131", "what is the prerequisite for cmpe 131"],
            "responses": ["For a CMPE major, CMPE 126 with a C- or better. For a SE major, CS 46B with a C- or better.", "This class is called Software Engineering 1 and it is a class about team-based projects that covers software development lifecycle activities like project planning and management requirements analysis and requirement specification."],
            "context": [""]
    },
    {"tag": "cmpe131",
            "patterns": ["what is the prereq for cmpe 131", "what is the prerequisite for cmpe 131"],
            "responses": ["For a CMPE major, CMPE 126 with a C- or better. For a SE major, CS 46B with a C- or better.", "This class is called Software Engineering 1 and it is a class about team-based projects that covers software development lifecycle activities like project planning and management requirements analysis and requirement specification."],
            "context": [""]
    },
    {"tag": "cmpe 120",
            "patterns": ["what is the prereq for cmpe 120", "what is the prerequisite for cmpe 120"],
            "responses": ["CMPE 50 or CS 46B with a C- or better.", "This class is called Computer Organization and Architecture and it is about the introduction to computer organization and architecture, system buses, internal memory and external memory, input/output, central processing unit CPU, etc."],
            "context": [""]
    },
    {"tag": "cmpe120",
            "patterns": ["what is the prereq for cmpe 120", "what is the prerequisite for cmpe 120"],
            "responses": ["CMPE 50 or CS 46B with a C- or better.", "This class is called Computer Organization and Architecture and it is about the introduction to computer organization and architecture, system buses, internal memory and external memory, input/output, central processing unit CPU, etc."],
            "context": [""]
    },
    {"tag": "cmpe 102",
            "patterns": ["what is the prereq for cmpe 102", "what is the prerequisite for cmpe 102"],
            "responses": ["CMPE 50 or CS 46B with a C- or better.", "This class is called Assembly Language Programming which teaches assembly programming."],
            "context": [""]
    },
    {"tag": "cmpe102",
            "patterns": ["what is the prereq for cmpe 102", "what is the prerequisite for cmpe 102"],
            "responses": ["CMPE 50 or CS 46B with a C- or better.", "This class is called Assembly Language Programming which teaches assembly programming."],
            "context": [""]
    },
    {"tag": "cmpe 133",
            "patterns": ["what is the prereq for cmpe 133", "what is the prerequisite for cmpe 133"],
            "responses": ["CMPE 131 with a C- or better.", "This class is called Software Engineering 2 and it is a another class that focuses on team-based projects."],
            "context": [""]
    },
    {"tag": "cmpe133",
            "patterns": ["what is the prereq for cmpe 133", "what is the prerequisite for cmpe 133"],
            "responses": ["CMPE 131 with a C- or better.", "This class is called Software Engineering 2 and it is a another class that focuses on team-based projects."],
            "context": [""]
    },
    {"tag": "cmpe 148",
            "patterns": ["what is the prereq for cmpe 148", "what is the prerequisite for cmpe 148"],
            "responses": ["For a se major: CMPE 120 and CS 146 with a C- or better. For a cmpe major: CMPE 124 and CMPE 126 with a C- or better.", "This class is called Computer Networks 1 and goes over network architecture, layering model, standards, protocol examples for ISO and TCP/IP layer."],
            "context": [""]
    },
    {"tag": "cmpe148",
            "patterns": ["what is the prereq for cmpe 148", "what is the prerequisite for cmpe 148"],
            "responses": ["For a se major: CMPE 120 and CS 146 with a C- or better. For a cmpe major: CMPE 124 and CMPE 126 with a C- or better.", "This class is called Computer Networks 1 and goes over network architecture, layering model, standards, protocol examples for ISO and TCP/IP layer."],
            "context": [""]
    },
    {"tag": "cmpe 165",
            "patterns": ["what is the prereq for cmpe 165", "what is the prerequisite for cmpe 165"],
            "responses": ["CMPE 131 with a C- or better", "This class is called Software Engineering Process Management which covers the integrated approach to managing development within small teams."],
            "context": [""]
    },
    {"tag": "cmpe165",
            "patterns": ["what is the prereq for cmpe 165", "what is the prerequisite for cmpe 165"],
            "responses": ["CMPE 131 with a C- or better", "This class is called Software Engineering Process Management which covers the integrated approach to managing development within small teams."],
            "context": [""]
    },
    {"tag": "cmpe 172",
            "patterns": ["what is the prereq for cmpe 172", "what is the prerequisite for cmpe 172"],
            "responses": ["CMPE 142 or CS 149 with a C- or better", "This class is called Enterprise Software Platforms and covers network operating systems, DBMS, transaction monitors, groupware, distributed objects, system management and the web."],
            "context": [""]
    },
    {"tag": "cmpe172",
            "patterns": ["what is the prereq for cmpe 172", "what is the prerequisite for cmpe 172"],
            "responses": ["CMPE 142 or CS 149 with a C- or better", "This class is called Enterprise Software Platforms and covers network operating systems, DBMS, transaction monitors, groupware, distributed objects, system management and the web."],
            "context": [""]
    },
    {"tag": "cmpe 187",
            "patterns": ["what is the prereq for cmpe 187", "what is the prerequisite for cmpe 187"],
            "responses": ["CMPE 131 with a C- or better.", "This class is called Software Quality Engineering and goes over software testing, software unit testing and software security testing."],
            "context": [""]
    },
    {"tag": "cmpe187",
            "patterns": ["what is the prereq for cmpe 187", "what is the prerequisite for cmpe 187"],
            "responses": ["CMPE 131 with a C- or better.", "This class is called Software Quality Engineering and goes over software testing, software unit testing and software security testing."],
            "context": [""]
    },
    {"tag": "cmpe 195a",
            "patterns": ["what is the prereq for cmpe 195a", "what is the prerequisite for cmpe 195a"],
            "responses": ["For CMPE majors: CMPE 125, CMPE 127, CMPE 130, CMPE 131 with a C- or better and ENGR 100W with a C- or better \n for SE majors: CMPE 133, CS 146, ISE 130 or MATH 161A with a C- or better and ENGR 100W with a C or better", "This class is called Senior Design Project 1 and is about a comprehensive plan and preliminary design of a group computer/software engineering project."],
            "context": [""]
    },
    {"tag": "cmpe195a",
            "patterns": ["what is the prereq for cmpe 195a", "what is the prerequisite for cmpe 195a"],
            "responses": ["For CMPE majors: CMPE 125, CMPE 127, CMPE 130, CMPE 131 with a C- or better and ENGR 100W with a C- or better \n for SE majors: CMPE 133, CS 146, ISE 130 or MATH 161A with a C- or better and ENGR 100W with a C or better", "This class is called Senior Design Project 1 and is about a comprehensive plan and preliminary design of a group computer/software engineering project."],
            "context": [""]
    },
    {"tag": "cmpe 195b",
            "patterns": ["what is the prereq for cmpe 195b", "what is the prerequisite for cmpe 195b"],
            "responses": ["CMPE 195A with a C or better and must be a junior or senior", "This class is called Senior Design Project 2 and is focused on implementing the project that was started in CMPE 195a."],
            "context": [""]
    },
    {"tag": "cmpe195b",
            "patterns": ["what is the prereq for cmpe 195b", "what is the prerequisite for cmpe 195b"],
            "responses": ["CMPE 195A with a C or better and must be a junior or senior", "This class is called Senior Design Project 2 and is focused on implementing the project that was started in CMPE 195a."],
            "context": [""]
    },
    {"tag": "cmpe 195",
            "patterns": ["what is the prereq for cmpe 195a", "what is the prerequisite for cmpe 195a"],
            "responses": ["Ask the question again but specificy cmpe 195a or cmpe 195b", "This class is about the Senior Design Project and its split into 2 parts."],
            "context": [""]
    },
    {"tag": "cmpe195",
            "patterns": ["what is the prereq for cmpe 195a", "what is the prerequisite for cmpe 195a"],
            "responses": ["Ask the question again but specificy cmpe 195a or cmpe 195b", "This class is about the Senior Design Project and its split into 2 parts."],
            "context": [""]
    },
    {"tag": "engr 195a",
            "patterns": ["what is the prereq for engr 195a", "what is the prerequisite for engr 195a"],
            "responses": ["ENGR 100W with a C or better", "This class is called Global and Social Issues in Engineering which is an interdisciplinary seminar treating social and global impacts of technology and engineering."],
            "context": [""]
    },
    {"tag": "engr195a",
            "patterns": ["what is the prereq for engr 195a", "what is the prerequisite for engr 195a"],
            "responses": ["ENGR 100W with a C or better", "This class is called Global and Social Issues in Engineering which is an interdisciplinary seminar treating social and global impacts of technology and engineering."],
            "context": [""]
    },
    {"tag": "engr 195b",
            "patterns": ["what is the prereq for engr 195b", "what is the prerequisite for engr 195b"],
            "responses": ["ENGR 195a with a C or better", "This class is called Global and Social Issues in Engineering wich does a case study approach to the relationship of engineering to social, ethical and cultural aspects of the broader community both in the U.S. and worldwide."],
            "context": [""]
    },
    {"tag": "engr195b",
            "patterns": ["what is the prereq for engr 195b", "what is the prerequisite for engr 195b"],
            "responses": ["ENGR 195a with a C or better", "This class is called Global and Social Issues in Engineering wich does a case study approach to the relationship of engineering to social, ethical and cultural aspects of the broader community both in the U.S. and worldwide."],
            "context": [""]
    },
    {"tag": "engr 195",
            "patterns": ["what is the prereq for engr 195b", "what is the prerequisite for engr 195b"],
            "responses": ["Ask the question again but specificy engr 195a or engr 195b", "This class is called Global and Social Issues in Engineering and is split into two parts."],
            "context": [""]
    },
    {"tag": "engr195",
            "patterns": ["what is the prereq for engr 195b", "what is the prerequisite for engr 195b"],
            "responses": ["Ask the question again but specificy engr 195a or engr 195b", "This class is called Global and Social Issues in Engineering and is split into two parts."],
            "context": [""]
    },
    {"tag": "ise 164",
            "patterns": ["what is the prereq for ise 164", "what is the prerequisite for ise 164"],
            "responses": ["just be in your junior year", "This class is called Computer and Human Interaction which is an introduction to human/computer interaction, paradigms for interaction, human performance capabilities, computer input/output device analysis and design."],
            "context": [""]
    },
    {"tag": "ise164",
            "patterns": ["what is the prereq for ise 164", "what is the prerequisite for ise 164"],
            "responses": ["just be in your junior year", "This class is called Computer and Human Interaction which is an introduction to human/computer interaction, paradigms for interaction, human performance capabilities, computer input/output device analysis and design."],
            "context": [""]
    },
    {"tag": "how many units should i take",
            "patterns": ["how many units should i take", "how many units should i take each semester"],
            "responses": ["15 units is the suggested amount to graduate on time.", "15 units is the suggested amount to graduate on time."],
            "context": [""]
    },
    {"tag": "cmpe 137",
            "patterns": ["what is the prereq for cmpe 137", "what is the prerequisite for cmpe 137"],
            "responses": ["CMPE 131 with a C- or better", "This class is called Wireless Mobile Software Engneering which is about mobility analysis, design principles, techniques, and methods for software systems on a variety of wireless and mobile Internet based computing and communication platforms, such as advanced pocket/tablet PCs, GPS, Bluetooth, Infrared, Wi-Fi, and RFID."],
            "context": [""]
    },
    {"tag": "cmpe137",
            "patterns": ["what is the prereq for cmpe 137", "what is the prerequisite for cmpe 137"],
            "responses": ["CMPE 131 with a C- or better", "This class is called Wireless Mobile Software Engneering which is about mobility analysis, design principles, techniques, and methods for software systems on a variety of wireless and mobile Internet based computing and communication platforms, such as advanced pocket/tablet PCs, GPS, Bluetooth, Infrared, Wi-Fi, and RFID."],
            "context": [""]
    },
    {"tag": "cmpe 139",
            "patterns": ["what is the prereq for cmpe 137", "what is the prerequisite for cmpe 137"],
            "responses": ["CMPE 126 or CS 146 with a C- or better", "This class is Introduction to data management and data mining, data preproccing, OLAP and data warehousing."],
            "context": [""]
    },
    {"tag": "cmpe139",
            "patterns": ["what is the prereq for cmpe 137", "what is the prerequisite for cmpe 137"],
            "responses": ["CMPE 126 or CS 146 with a C- or better", "This class is Introduction to data management and data mining, data preproccing, OLAP and data warehousing."],
            "context": [""]
    },
    {"tag": "cmpe 152",
            "patterns": ["what is the prereq for cmpe 152", "what is the prerequisite for cmpe 152"],
            "responses": ["CMPE 126 and CMPE 102 with a C- or better", "This class goes over the principles of lexical analysis, finite state automata and parsing."],
            "context": [""]
    },
    {"tag": "cmpe152",
            "patterns": ["what is the prereq for cmpe 152", "what is the prerequisite for cmpe 152"],
            "responses": ["CMPE 126 and CMPE 102 with a C- or better", "This class goes over the principles of lexical analysis, finite state automata and parsing."],
            "context": [""]
    },
    {"tag": "cmpe 185",
            "patterns": ["what is the prereq for cmpe 185", "what is the prerequisite for cmpe 185"],
            "responses": ["ISE 130 or MATH 161A and MATH 33LA and CMPE 126 or CS 146 with a C- or better", "This class is called Automonous Mobile Robots and it goges over basic concepts and alogrithms for mobile robots."],
            "context": [""]
    },
    {"tag": "cmpe185",
            "patterns": ["what is the prereq for cmpe 185", "what is the prerequisite for cmpe 185"],
            "responses": ["ISE 130 or MATH 161A and MATH 33LA and CMPE 126 or CS 146 with a C- or better", "This class is called Automonous Mobile Robots and it goges over basic concepts and alogrithms for mobile robots."],
            "context": [""]
    },
    {"tag": "cmpe 181",
            "patterns": ["what is the prereq for cmpe 181", "what is the prerequisite for cmpe 181"],
            "responses": ["For a CMPE major: CMPE 124 and CMPE 126 with a C- or better. For SE major: CMPE 120 and CS 146 with a C- or better.", "This class is called Internet of Things Platforms and it goes over landscape, fundementals, architecture, standards and protocols."],
            "context": [""]
    },
    {"tag": "cmpe181",
            "patterns": ["what is the prereq for cmpe 181", "what is the prerequisite for cmpe 181"],
            "responses": ["For a CMPE major: CMPE 124 and CMPE 126 with a C- or better. For SE major: CMPE 120 and CS 146 with a C- or better.", "This class is called Internet of Things Platforms and it goes over landscape, fundementals, architecture, standards and protocols."],
            "context": [""]
    },
    {"tag": "cmpe 182",
            "patterns": ["what is the prereq for cmpe 182", "what is the prerequisite for cmpe 182"],
            "responses": ["CMPE 126 or CS 146 with a C- or better.", "This class is called Internet of Things Security and it goes over system design, vulnerabilities, attacks, and countermeasures, principles of privacy-by-design, secure IoT system development and lifecycle."],
            "context": [""]
    },
    {"tag": "cmpe182",
            "patterns": ["what is the prereq for cmpe 182", "what is the prerequisite for cmpe 182"],
            "responses": ["CMPE 126 or CS 146 with a C- or better.", "This class is called Internet of Things Security and it goes over system design, vulnerabilities, attacks, and countermeasures, principles of privacy-by-design, secure IoT system development and lifecycle."],
            "context": [""]
    },
    {"tag": "cmpe 183",
            "patterns": ["what is the prereq for cmpe 183", "what is the prerequisite for cmpe 183"],
            "responses": ["CMPE 126 or CS 146 with a C- or better.", "This class is called Cryptocurrencies and Blockchains and it goes over the technical aspects of cryptocurrencies, blockchains, distributed consensus, and decentralized applications."],
            "context": [""]
    },
    {"tag": "cmpe183",
            "patterns": ["what is the prereq for cmpe 183", "what is the prerequisite for cmpe 183"],
            "responses": ["CMPE 126 or CS 146 with a C- or better.", "This class is called Cryptocurrencies and Blockchains and it goes over the technical aspects of cryptocurrencies, blockchains, distributed consensus, and decentralized applications."],
            "context": [""]
    },
    {"tag": "cmpe 185",
            "patterns": ["what is the prereq for cmpe 185", "what is the prerequisite for cmpe 185"],
            "responses": ["ISE 130 or MATH 161A and MATH 33LA and CMPE 126 or CS 146 with a C- or better", "This class is called Autonomous Mobile Robots and it covers the basic concepts and algorithms for mobile robots that act autonomously in complex environments."],
            "context": [""]
    },
    {"tag": "cmpe185",
            "patterns": ["what is the prereq for cmpe 185", "what is the prerequisite for cmpe 185"],
            "responses": ["ISE 130 or MATH 161A and MATH 33LA and CMPE 126 or CS 146 with a C- or better", "This class is called Autonomous Mobile Robots and it covers the basic concepts and algorithms for mobile robots that act autonomously in complex environments."],
            "context": [""]
    },
    {"tag": "cmpe 188",
            "patterns": ["what is the prereq for cmpe 188", "what is the prerequisite for cmpe 188"],
            "responses": ["CMPE 126 or CS 146 with a  C- or better", "This class is called Macine Learning for Big Data and it is an introduction to machine learning and pattern recognition for big data analytics; machine learning concepts, theories, approaches, algorithms, and big data analytic applications."],
            "context": [""]
    },
    {"tag": "cmpe188",
            "patterns": ["what is the prereq for cmpe 188", "what is the prerequisite for cmpe 188"],
            "responses": ["CMPE 126 or CS 146 with a  C- or better", "This class is called Macine Learning for Big Data and it is an introduction to machine learning and pattern recognition for big data analytics; machine learning concepts, theories, approaches, algorithms, and big data analytic applications."],
            "context": [""]
    },
    {"tag": "cmpe 189",
            "patterns": ["what is the prereq for cmpe 189", "what is the prerequisite for cmpe 189"],
            "responses": ["You just need instructor consent", "This class is called Special Topics in Computer Engineering and goes over advanced topics in computer engineering, the content changes from semester to semester."],
            "context": [""]
    },
    {"tag": "cmpe189",
            "patterns": ["what is the prereq for cmpe 189", "what is the prerequisite for cmpe 189"],
            "responses": ["You just need instructor consent", "This class is called Special Topics in Computer Engineering and goes over advanced topics in computer engineering, the content changes from semester to semester."],
            "context": [""]
    },
    {"tag": "cs 116a",
            "patterns": ["what is the prereq for cs 116a", "what is the prerequisite for cs 116a"],
            "responses": ["MATH 31, CS 146 with a grade of C- or better and previous experience in C/C++", "This class is called Introduction to Computer Graphics and goes over vector geometry, geometric transformations and the graphics pipeline."],
            "context": [""]
    },
    {"tag": "cs116a",
            "patterns": ["what is the prereq for cs 116a", "what is the prerequisite for cs 116a"],
            "responses": ["MATH 31, CS 146 with a grade of C- or better and previous experience in C/C++", "This class is called Introduction to Computer Graphics and goes over vector geometry, geometric transformations and the graphics pipeline."],
            "context": [""]
    },
    {"tag": "cs 134",
            "patterns": ["what is the prereq for cs 134", "what is the prerequisite for cs 134"],
            "responses": ["CS 146 and either CS 151 or CMPE 135 with a C- or better", "This class is called Computer Game Design and Programming and it covers the architectures and object-oriented patterns for computer game design. Animation, simulation, user interfaces, graphics, and intelligent behaviors."],
            "context": [""]
    },
    {"tag": "cs134",
            "patterns": ["what is the prereq for cs 134", "what is the prerequisite for cs 134"],
            "responses": ["CS 146 and either CS 151 or CMPE 135 with a C- or better", "This class is called Computer Game Design and Programming and it covers the architectures and object-oriented patterns for computer game design. Animation, simulation, user interfaces, graphics, and intelligent behaviors."],
            "context": [""]
    },
    {"tag": "cs 152",
            "patterns": ["what is the prereq for cs 152", "what is the prerequisite for cs 152"],
            "responses": ["CS 151 or CMPE 135 with a C- or better", "This class is called Programming Paradigms and it goes over the programming language syntax and semantics of various languages."],
            "context": [""]
    },
    {"tag": "cs152",
            "patterns": ["what is the prereq for cs 152", "what is the prerequisite for cs 152"],
            "responses": ["CS 151 or CMPE 135 with a C- or better", "This class is called Programming Paradigms and it goes over the programming language syntax and semantics of various languages."],
            "context": [""]
    }
]

#training data about what gpa is needed to transfer
gpaToTransfer = [
    "what gpa do i need to transfer into software engineering?",
    "how many course requirements have you completed?",
    "7",
    "At least a 3.4 GPA is reccomended.",
    "seven",
    "At least a 3.4 GPA is reccomended.",
    "Seven",
    "At least a 3.4 GPA is reccomended",
    "6",
    "At least a 3.6 GPA is reccomended.",
    "six",
    "At least a 3.6 GPA is reccomended.",
    "Six",
    "At least a 3.6 GPA is reccomended",
    "5",
    "At least a 3.8 GPA is reccomended.",
    "five",
    "At least a 3.8 GPA is reccomended.",
    "Five",
    "At least a 3.8 GPA is reccomended",
    "4",
    "At least a 4.0 GPA is reccomended.",
    "four",
    "At least a 4.0 GPA is reccomended.",
    "Four",
    "At least a 4.0 GPA is reccomended",
    "3",
    "At least a 4.2 GPA is reccomended.",
    "three",
    "At least a 4.2 GPA is reccomended.",
    "Three",
    "At least a 4.2 GPA is reccomended",
    "2",
    "You need at least 3 course requirements.",
    "two",
    "You need at least 3 course requirements.",
    "Two",
    "You need at least 3 course requirements.",
    "1",
    "You need at least 3 course requirements.",
    "one",
    "You need at least 3 course requirements.",
    "One",
    "You need at least 3 course requirements.",
    "0",
    "You need at least 3 course requirements.",
    "zero",
    "You need at least 3 course requirements.",
    "Zero",
    "You need at least 3 course requirements.",
    "what gpa do i need to get into computer engineering",
    "how many course requirements have you completed?",
    "7",
    "At least a 2.8 GPA is reccomended.",
    "seven",
    "At least a 2.8 GPA is reccomended.",
    "Seven",
    "At least a 2.8 GPA is reccomended",
    "6",
    "At least a 3.0 GPA is reccomended.",
    "six",
    "At least a 3.0 GPA is reccomended.",
    "Six",
    "At least a 3.0 GPA is reccomended",
    "5",
    "At least a 3.2 GPA is reccomended.",
    "five",
    "At least a 3.2 GPA is reccomended.",
    "Five",
    "At least a 3.2 GPA is reccomended",
    "4",
    "At least a 3.4 GPA is reccomended.",
    "four",
    "At least a 3.4 GPA is reccomended.",
    "Four",
    "At least a 3.4 GPA is reccomended",
    "3",
    "At least a 3.6 GPA is reccomended.",
    "three",
    "At least a 3.6 GPA is reccomended.",
    "Three",
    "At least a 3.6 GPA is reccomended",
    "2",
    "At least a 3.8 GPA is reccomended.",
    "two",
    "At least a 3.8 GPA is reccomended.",
    "Two",
    "At least a 3.8 GPA is reccomended.",
    "1",
    "At least a 4.0 GPA is reccomended.",
    "one",
    "At least a 4.0 GPA is reccomended.",
    "One",
    "At least a 4.0 GPA is reccomended.",
    "0",
    "At least a 4.2 GPA is reccomended.",
    "zero",
    "At least a 4.2 GPA is reccomended.",
    "Zero",
    "At least a 4.2 GPA is reccomended."
]

#training data for who someone's advisor is
advisor = [
    "Who is my advisor?",
    "What is the first letter your last name?",
    "who is my advisor?",
    "What is the first letter of your last name?",
    "a",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "b",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "c",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "d",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "e",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "f",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "g",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "h",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "i",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "j",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "k",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "l",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "m",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "n",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "o",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "p",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "q",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "r",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "s",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "t",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "u",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "v",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "w",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "x",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "y",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "z",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "A",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "B",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "C",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "D",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "E",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "F",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "G",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "H",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "I",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "J",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "K",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "L",
    "Your advisor is Christine Watson. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "M",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "N",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "O",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "P",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "Q",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "R",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "S",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "T",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "U",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "V",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "W",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "X",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "Y",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "Z",
    "Your advisor is Monica Serna. You can book an appointment here: https://sjsu.campus.eab.com/student/appointments/new",
    "Where can I apply for an appointment with my advisor?",
    "https://sjsu.campus.eab.com/"
]
